# Site settings
title: Vivek Yadav Project Portfolio
email: vivek.yadav@gmail.com
description: "Compilation of my data science and machine learning projects."
baseurl: ""
url: "http://vxy10.github.io"
github_username:  vxy10

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

